name: TestPROGPOE

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: List contents
        run: ls

      - name: Compile classes
        working-directory: ./src
        run: |
          javac -cp "../lib/junit-platform-console-standalone-1.6.0.jar" ./st10228343/ST10228343.java ./st10228343/Login.java ./st10228343/Tasks.java "../test/st10228343/LoginTest.java"

      - name: List contents of src directory after compile
        working-directory: ./src/st10228343
        run: ls

      - name: Copy compiled classes to test resources directory
        working-directory: ./src/st10228343
        run: cp -t "../../test/st10228343" ST10228343.class Login.class Tasks.class

      - name: Copy compiled test classes to test resources directory
        working-directory: ./test/st10228343
        run: |
          if [ ! -f "../../test/st10228343/LoginTest.class" ]; then
            cp LoginTest.class "../../test/st10228343/LoginTest.class"
          fi

      - name: List contents of test package
        working-directory: ./test/st10228343
        run: ls

      - name: Run LoginTest and generate report
        working-directory: ./test
        run: java -jar "../lib/junit-platform-console-standalone-1.6.0.jar" -cp "." --select-class st10228343.LoginTest





